### ISSUE TITLE
To and from

### ISSUE THREAD

**Issue by joeyespo** [tomekwojcik/envelopes#4]
This can be made even more humanistic by using `to` and `from` instead of `to_addr` and `from_addr` since "address" is usually implied when talking about email.

You could then allow `to` to accept a list as well as a single string without having to add another argument.

**Comment by tomekwojcik** [comment]
Hi,
I'm happy to inform you that it's already done and has been applied in c68300c33475768f8e992d8edd7b3d31e4c1db55 :).

As far as naming go - since I couldn't use `from` in keyword args I decided to leave `to_addr` and `from_addr` as they were. Plus, I adjusted the rest of the API to match this convention. Also, `to_addr` field is internally converted to list of addresses and behaves exactly like `cc_addr`.

Thanks for filing the issue and for your interest in the project :).

**Comment by joeyespo** [comment]
Ah right, can't use `from`. I should know better =) 

I'll just suggest one more then, `to` and `sender`. Is `from_addr` optional? It'd be an even better reason to use `to`, at the very least. Oh well!

Thanks for adding this capability. This is an excellent project!

**Comment by tomekwojcik** [comment]
Hi,
after giving the issue a lot of thought I decided to leave the API as is. While your `sender` and `to` suggestion looks nice I think it suffers from being inconsistent with SMTP naming. I'd much rather annoy the users by forcing them to add `_addr` suffix than confuse them.

`from_addr` is as optional as the rest of the args. However, I'm not sure about how certain SMTP servers would react when receiving a message without `From` header. I'll check that one later.

Thanks and have a good day (or night) :).
